import os
import json
import subprocess
import sys

def load_env(path=".env"):
    env = {}
    if os.path.exists(path):
        with open(path, "r", encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if not line or line.startswith("#"):
                    continue
                if "=" in line:
                    k, v = line.split("=", 1)
                    env[k.strip()] = v.strip()
    return env

def main():
    print("====================================================")
    print("        Athena DIAGNOSTIC & SYNC TESTER")
    print("====================================================\n")

    # 1. Check if .env file exists
    if not os.path.exists(".env"):
        print("[FAIL] '.env' configuration file not found in current folder!")
        print("Please configure your .env file first.")
        return

    env = load_env()
    server_url = env.get("ROCKET_SERVER_URL")
    user_id = env.get("ROCKET_USER_ID")
    auth_token = env.get("ROCKET_AUTH_TOKEN")
    workai_user = env.get("WORKAI_USERNAME")

    # 2. Check configuration variables
    has_error = False
    print("--- Checking Configurations ---")
    if not server_url or "your_" in server_url:
        print("[-] ROCKET_SERVER_URL: MISSING or default value")
        has_error = True
    else:
        print(f"[+] ROCKET_SERVER_URL: {server_url}")

    if not user_id or "your_" in user_id:
        print("[-] ROCKET_USER_ID: MISSING or default value")
        has_error = True
    else:
        print(f"[+] ROCKET_USER_ID: {user_id}")

    if not auth_token or "your_" in auth_token:
        print("[-] ROCKET_AUTH_TOKEN: MISSING or default value")
        has_error = True
    else:
        print("[+] ROCKET_AUTH_TOKEN: Configured (Hidden)")

    if not workai_user or "your_" in workai_user:
        print("[-] WORKAI_USERNAME: MISSING or default value")
        has_error = True
    else:
        print(f"[+] WORKAI_USERNAME: {workai_user}")

    if has_error:
        print("\n[FAIL] Some configuration parameters are missing or invalid in your '.env' file.")
        print("Please edit the '.env' file in your workspace folder with your actual credentials and try again.")
        return
    else:
        print("[PASS] Configurations validated successfully!\n")

    # 3. Try to run sync_rocket.py
    print("--- Executing Rocket.Chat Sync ---")
    try:
        # Run sync_rocket.py using the same python interpreter
        result = subprocess.run([sys.executable, "sync_rocket.py"], capture_output=True, text=True, encoding="utf-8")
        print(result.stdout)
        
        if result.stderr:
            print(f"[WARNING] Stderr output:\n{result.stderr}")
            
        if result.returncode != 0:
            print("[FAIL] sync_rocket.py execution failed with non-zero exit code.")
            return
            
    except Exception as e:
        print(f"[FAIL] Failed to run sync_rocket.py: {e}")
        return

    # 4. Check if chat_raw.json was generated and verify contents
    if not os.path.exists("chat_raw.json"):
        print("[FAIL] 'chat_raw.json' was not generated by the sync script.")
        return

    try:
        with open("chat_raw.json", "r", encoding="utf-8") as f:
            data = json.load(f)
            
        print("\n--- Sync Summary Results ---")
        if not data:
            print("[INFO] Connection succeeded, but no messages or active conversations were found from today (since 00:00 AM).")
            print("Make sure you had some active discussions today in Rocket.Chat!")
        else:
            print(f"[SUCCESS] Successfully retrieved chats from {len(data)} active rooms today:")
            total_msgs = 0
            for idx, room in enumerate(data, 1):
                name = room.get("room_name")
                rtype = room.get("room_type")
                count = len(room.get("messages", []))
                total_msgs += count
                print(f"   {idx}. [{rtype.upper()}] {name}: {count} messages")
            print(f"\n[TOTAL] Fetched {total_msgs} messages successfully!")
            print("[STATUS] Ready for AI filtering and work-logging!")
            
    except Exception as e:
        print(f"[FAIL] Error reading generated 'chat_raw.json': {e}")

if __name__ == "__main__":
    main()
